### ISSUE TITLE
add async buffer support, non blocking buffer capability

### ISSUE THREAD

**Issue by tablatronix** [pvizeli/SerialCommandParser#2]
It would be nice to be able to add to buffer during active loops with no delay, then perform parse when newline comes in.

Right now readFromSerial is blocking.

**Comment by tablatronix** [comment]
I am just wrapping it in a   `if(Serial.available() > 0) {` condition for now, but to be able to pass strings into parsecmd, and to be able to add directly to buffer as characters etc might be useful if one need to use with something other than a streams etc.

**Comment by pvizeli** [comment]
Can you make a PR with that change?
