### ISSUE TITLE
BUG parses empty buffers

### ISSUE THREAD

**Issue by tablatronix** [pvizeli/SerialCommandParser#5]
test
```
    CmdBuffer<32> myBuffer;
    if (cmdParser.parseCmd(&myBuffer) != CMDPARSER_ERROR) Serial.println("myBuffer not empty"); // but buffer IS empty
```
is not caught by
```
    // buffer is not okay
    if (buffer == NULL || bufferSize == 0) {
        return CMDPARSER_ERROR;
    }
```
parses empty buffers without error, not sure if this is correct, cause then subsequent calls are useless
cmdParser.getCommand(); is empty
cmdParser.getCmdParam(1) throws exceptions even , if you are not checking for 0 param count first ( this might be a second bug that can be addressed to avoid exceptions.

**Comment by tablatronix** [comment]
I understand why a NULL check is failing, it will never be null


But i would think

buffer == 0 would work but it does not, I guess we can just assume buffer[0] == 0x00 is empty and useless, but then you cannot parse empty newlines

**Comment by tablatronix** [comment]
well I guess you cannot do that at all.

I can only think of doing memcmp with an empty buffer or a loop check or change the functionality of [0] == 0x00 to return something other than paramcnt

**Comment by pvizeli** [comment]
Fix with https://github.com/pvizeli/CmdParser/commit/943873564c3ecbde18e52505bf12f3d7961192cd
